pipeline:
  name: aferfaef
  identifier: aferfaef
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cds
        identifier: cds
        template:
          templateRef: q34t534dvss
          versionLabel: b1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: adevca
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
