pipeline:
  name: asdgfdsgsdfg
  identifier: asdgfdsgsdfg
  projectIdentifier: adithya_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        tags: {}
        template:
          templateRef: teasra_asfasfd
          versionLabel: sd32e
          gitBranch: b1-patch-b1-patch
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
    - stage:
        name: t1
        identifier: t1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: <+input>
              namespace: <+input>
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: <+input>
                    image: <+input>
                    shell: Sh
                    command: echo 123
                  description: dfgsdfgsd
  properties:
    ci:
      codebase:
        connectorRef: adi_github
        repoName: demo
        build: <+input>
