pipeline:
  name: case4sept19
  identifier: case4sept19
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stage15RemoteMainR1
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: adfvdafg
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
