pipeline:
  name: case4
  identifier: case4
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: hkg
        identifier: hkg
        template:
          templateRef: stage15RemoteMainR1
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: adfvdafg
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
