pipeline:
  name: case4Dec19QA
  identifier: case4Dec19QA
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: qaStageMainDec19
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: dasf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
