pipeline:
  name: demoPipelinesept08
  identifier: demoPipelinesept08
  projectIdentifier: demo_gitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: stageTemplateDemo08MAin
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: stage_approval
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
    - stage:
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: stage approval
                  identifier: stage_approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: approval from stage template testRepo main
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        name: stage2
        identifier: stage2
        tags: {}
