pipeline:
  name: fgsdfg
  identifier: fgsdfg
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsgf
        identifier: dsgf
        template:
          templateRef: q1stage
          versionLabel: bvw
          gitBranch: main
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: fdas
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
