pipeline:
  name: iohoh
  identifier: iohoh
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: j
        identifier: j
        template:
          templateRef: q1stage
          versionLabel: bvw
          gitBranch: main
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: fdas
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
