pipeline:
  name: oldGitSyncJan9
  identifier: oldGitSyncJan9
  projectIdentifier: oldGitSync
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: kj
        identifier: kj
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: df
                  identifier: df
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
