pipeline:
  name: p4Nested14R2Patch
  identifier: p4Nested14R2Patch
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: nestedStageMain14R1
          versionLabel: v1
