pipeline:
  name: p6Nested14PatchR2
  identifier: p6Nested14PatchR2
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: nestedStageMain14R1
          versionLabel: v1
