pipeline:
  name: pipeline remote p1 12341234
  identifier: pipeline_remote_p1_12341234
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: zxc
        identifier: zxc
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: asd
                  identifier: asd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: <+input>
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
