pipeline:
  name: sept7p8
  identifier: sept7p8
  projectIdentifier: demo_gitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: sept7StageRemotee
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: stage_approval
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
