pipeline:
  name: sept7p2
  identifier: sept7p2
  projectIdentifier: demo_gitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: sept7NestedTemplate
          versionLabel: v1
