pipeline:
  name: test batching qaaaw
  identifier: test_batching_qaaaw
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: m
        identifier: m
        template:
          templateRef: account.stage_m_connector
          versionLabel: v1
          gitBranch: main
    - stage:
        name: a
        identifier: a
        template:
          templateRef: account.stage_a_connector
          versionLabel: v1
          gitBranch: main
    - stage:
        name: aa
        identifier: aa
        template:
          templateRef: account.stage_aa_connector
          versionLabel: v12
          gitBranch: main
    - stage:
        name: a2
        identifier: a2
        template:
          templateRef: account.stage_a2_tempalte
          versionLabel: v23
          gitBranch: main
