pipeline:
  name: test trigger based123
  identifier: test_trigger_based
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsf
        identifier: dsf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsfs
                  identifier: dsfs
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following inform
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
